# Generated by Django 3.1.7 on 2022-05-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('number_order', models.CharField(blank=True, max_length=100, null=True)),
                ('price_dolars', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('price_rubles', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('data_deliveries', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
